### ISSUE TITLE
Weird output on nuscenes

### ISSUE THREAD

**Issue by geekJZY** [georghess/neurad-studio#30]
Hi,

**Describe the bug**
Thanks for your contribution for this great work. I tried it out on Nuscenes, but I get some weird outputs with low quality. So I want to double check with you.

**To Reproduce**

I train the model on Nuscenes with 
``` bash
CUDA_VISIBLE_DEVICES=0 python nerfstudio/scripts/train.py neurader \
--pipeline.datamanager.num_processes=0 --vis tensorboard nuscenes-data 
```
Then I generated the video with
``` bash
CUDA_VISIBLE_DEVICES=0 python nerfstudio/scripts/render.py interpolate \
--output_path ./renders/neurader.mp4 \
--load_config /net/acadia14a/data/zjiang/projects/Diffusion/code/neurad-studio/outputs/unnamed/neurader/2024-06-03_112521/config.yml
```

**Expected behavior**
I expect the model to generate images with the quality shown in paper.

**Screenshots**
Here is the screenshots about the results I got.

![image](https://github.com/georghess/neurad-studio/assets/31909301/fae47e4c-3dd0-447b-87a8-6e1004e65587)

![image](https://github.com/georghess/neurad-studio/assets/31909301/89931ea1-5542-459d-9a9b-db3d9d82bdc3)

https://github.com/georghess/neurad-studio/assets/31909301/f6809578-277a-468f-be01-0462dc90243b

**Comment by atonderski** [comment]
There seem to multiple weird things going on here.

First, initial rendering quality is atrocious, need to investigate what is going on here. Since nuscenes lacks full pose information (z-component is missing), and the initial part is slightly downhill, I suspect this sequence requires pose optimization. Please try a training with `--pipeline.model.camera_optimizer.mode=S03xR3`

Secondly, when the static scene starts to look more reasonable (second half of video where the road has flattened out), the actors look really bad. This seems to be due time being frozen, which is controlled by the rendering script. I will look into this.

**Comment by atonderski** [comment]
Actors stopping was due to a poorly chosen default value in the rendering script. This was fixed [here](https://github.com/georghess/neurad-studio/commit/9ff5f7d279785cb9e6f77e78cd6548ddcd344916#diff-b8a6294020646e4be59904387fef33c3eb4407ed5dca71d2b7ff9c5f720e4093L622), so if you rerun on latest master the second half of the sequence should look much better :)

**Comment by Andyshen555** [comment]
@atonderski 
When I tried to reconstruct NuScenes videos, I figured out that it is blurry and flickering. Also, the vehicles shake left and right. My training configures are below:
 
    --max-num-iterations 60001\
    --machine.num-devices 2\
    --pipeline.model.eval_num_rays_per_chunk 32768 \
    --pipeline.datamanager.num_processes 8 \
    --pipeline.datamanager.train-num-lidar-rays-per-batch 16384 \
    --pipeline.datamanager.eval-num-lidar-rays-per-batch 8192 \
    --pipeline.datamanager.train-num-rays-per-batch 49152 \
    --pipeline.datamanager.eval-num-rays-per-batch 49152 \
    --pipeline.datamanager.train-num-images-to-sample-from 128 \
    --pipeline.datamanager.train-num-times-to-repeat-images 256 \
    --pipeline.model.sampling.proposal-field-1.grid.static.log2-hashmap-size 22\
    --pipeline.model.camera-optimizer.mode SO3xR3 \
    nuscenes-data \
    --data=/mnt/ssd/NIO/data/nuScene-mini \
    --sequence=scene-0061\
    --dataset_end_fraction=1.0 \
    --version=v1.0-mini \
    --cameras=all \

I used the interpolate for the render and it looks like :

https://github.com/user-attachments/assets/b715e68f-fb7f-4fce-a0f8-1aa35474abba

Can you please provide some insight to what I am doing wrong here?

Also, it would be helpful if you can provide your training config for NuScene in your paper.
Thank you.
